"""
Agent using MCP server-everything tools, monitored by llmsessioncontract.

Protocol (from Protocol Builder):
  !echo.?{echoResult.!get-sum.?{get-sumResult.end, get-sumError.end}, echoError.end}

Usage:
  python weather_agent.py                # happy path
  python weather_agent.py --echo-fail    # echo fails, takes echoError branch
  python weather_agent.py --sum-fail     # get-sum fails, takes get-sumError branch
  python weather_agent.py --violation    # out-of-order call
"""

import json
import sys

from llmcontract import Monitor

# ── Protocol (as generated by Protocol Builder) ─────────────
PROTOCOL = "!echo.?{echoResult.!get-sum.?{get-sumResult.end, get-sumError.end}, echoError.end}"

# ── Tool implementations (mimic MCP server-everything) ──────

def echo(message: str) -> dict:
    return {"echo": message}

def get_sum(a: float, b: float) -> dict:
    return {"sum": a + b}

# ── Monitored agent ─────────────────────────────────────────

def run_agent(echo_fails=False, sum_fails=False):
    print(f"\nProtocol: {PROTOCOL}")
    print(f"{'='*60}\n")

    monitor = Monitor(PROTOCOL)

    # Step 1: !echo
    print(f"[S{monitor.current_state}] Calling echo tool...")
    r = monitor.send("echo")
    print(f"  !echo -> {r}")

    if echo_fails:
        print(f"\n[S{monitor.current_state}] Echo failed!")
        r = monitor.receive("echoError")
        print(f"  ?echoError -> {r}")
        print(f"  Terminal: {monitor.is_terminal}")
        return

    result = echo("Hello from the monitored agent!")
    print(f"  Result: {result}")

    # Step 2: ?echoResult
    r = monitor.receive("echoResult")
    print(f"  ?echoResult -> {r}")

    # Step 3: !get-sum
    print(f"\n[S{monitor.current_state}] Calling get-sum tool...")
    r = monitor.send("get-sum")
    print(f"  !get-sum -> {r}")

    if sum_fails:
        print(f"\n[S{monitor.current_state}] get-sum failed!")
        r = monitor.receive("get-sumError")
        print(f"  ?get-sumError -> {r}")
        print(f"  Terminal: {monitor.is_terminal}")
        return

    result = get_sum(3, 5)
    print(f"  Result: {result}")

    # Step 4: ?get-sumResult
    r = monitor.receive("get-sumResult")
    print(f"  ?get-sumResult -> {r}")

    print(f"\n[S{monitor.current_state}] Done! Terminal: {monitor.is_terminal}")


def demo_violation():
    print(f"\nProtocol: {PROTOCOL}")
    print(f"{'='*60}")
    print("Attempting to call get-sum before echo completes...\n")

    monitor = Monitor(PROTOCOL)

    r = monitor.send("echo")
    print(f"[S{monitor.current_state}] !echo -> {r}")

    # VIOLATION: skip ?echoResult and try !get-sum directly
    r = monitor.send("get-sum")
    print(f"[S{monitor.current_state}] !get-sum -> {r}")
    print(f"  Halted: {monitor.is_halted}")

    r = monitor.receive("echoResult")
    print(f"  ?echoResult -> {r}")


if __name__ == "__main__":
    args = sys.argv[1:]

    if "--violation" in args:
        demo_violation()
    elif "--echo-fail" in args:
        run_agent(echo_fails=True)
    elif "--sum-fail" in args:
        run_agent(sum_fails=True)
    else:
        run_agent()
